import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import NavBar from "@/components/NavBar/NavBar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NavBar />
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
