import { Archivo } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <NavBar />
        <main>
          <Providers>{children}</Providers>
        </main>
        <Footer/>
      </body>
    </html>
  );
}

